# Generated by Django 5.2.1 on 2025-06-03 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BurntBlog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='uid',
            field=models.UUIDField(auto_created=True, primary_key=True, serialize=False, unique=True, verbose_name='Post UUID'),
        ),
    ]
