# Generated by Django 5.2.1 on 2025-06-03 20:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BurntBlog', '0002_alter_post_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='Date',
        ),
        migrations.RemoveField(
            model_name='post',
            name='Post Content',
        ),
        migrations.RemoveField(
            model_name='post',
            name='Post Title',
        ),
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.TextField(default='theres no post yet anyway', verbose_name='Post Content'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='theres no post yet anyway', verbose_name='Post Title'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Post UUID'),
        ),
    ]
